ktor:
    application:
        modules:
            - com.burdantap.ApplicationKt.module
    deployment:
        port: 2020
    request:
      size-limit: 10485760 # 10 MB
    http:
      multipart:
        max-file-size: 10485760 # 10 MB
        max-request-size: 20971520 # 20 MB

jwt:
  issuer: "https://0.0.0.0:2020"
  domain: "https://0.0.0.0:2020"
  audience: "aa11bb22cc33cc22bb11aa"
  realm: "burdantap server application"
